import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUI } from "@/providers/NextUI";
import connectDB from '../../config/connectMongo';

connectDB();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Fish Tank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased prose-sm sm:prose-base prose-headings:m-0 prose-p:m-0 prose-ul:m-0 prose-img:m-0 prose-hr:my-5`}
      >
        <NextUI>
          {children}
        </NextUI>
        <footer className="bg-gray-100 py-4 border-t mt-6">
          <div className="container mx-auto text-center">
            <div className="flex flex-col items-center gap-2 text-black">
              <p>Embedded project: Smart fish-tank</p>
              <p>Created by ya zee leng diew zoo ling</p>
              <a href="https://embed-api-flask-production.up.railway.app" target="_blank" rel="noopener noreferrer">
                <button className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
                  Get Notify
                </button>
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}